// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// process_district_all_vars_n_orders
List process_district_all_vars_n_orders(List variable_values, List neighbors, List weights, IntegerVector hex_indices, CharacterVector var_names);
RcppExport SEXP _hexsmoothR_process_district_all_vars_n_orders(SEXP variable_valuesSEXP, SEXP neighborsSEXP, SEXP weightsSEXP, SEXP hex_indicesSEXP, SEXP var_namesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type variable_values(variable_valuesSEXP);
    Rcpp::traits::input_parameter< List >::type neighbors(neighborsSEXP);
    Rcpp::traits::input_parameter< List >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type hex_indices(hex_indicesSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type var_names(var_namesSEXP);
    rcpp_result_gen = Rcpp::wrap(process_district_all_vars_n_orders(variable_values, neighbors, weights, hex_indices, var_names));
    return rcpp_result_gen;
END_RCPP
}
// process_district_all_vars
List process_district_all_vars(List variable_values, List first_neighbors, List second_neighbors, NumericVector weights, IntegerVector hex_indices, CharacterVector var_names);
RcppExport SEXP _hexsmoothR_process_district_all_vars(SEXP variable_valuesSEXP, SEXP first_neighborsSEXP, SEXP second_neighborsSEXP, SEXP weightsSEXP, SEXP hex_indicesSEXP, SEXP var_namesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type variable_values(variable_valuesSEXP);
    Rcpp::traits::input_parameter< List >::type first_neighbors(first_neighborsSEXP);
    Rcpp::traits::input_parameter< List >::type second_neighbors(second_neighborsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type hex_indices(hex_indicesSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type var_names(var_namesSEXP);
    rcpp_result_gen = Rcpp::wrap(process_district_all_vars(variable_values, first_neighbors, second_neighbors, weights, hex_indices, var_names));
    return rcpp_result_gen;
END_RCPP
}
// simple_smoothing_single_var
List simple_smoothing_single_var(NumericVector values, List first_neighbors, List second_neighbors, IntegerVector hex_indices);
RcppExport SEXP _hexsmoothR_simple_smoothing_single_var(SEXP valuesSEXP, SEXP first_neighborsSEXP, SEXP second_neighborsSEXP, SEXP hex_indicesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< List >::type first_neighbors(first_neighborsSEXP);
    Rcpp::traits::input_parameter< List >::type second_neighbors(second_neighborsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type hex_indices(hex_indicesSEXP);
    rcpp_result_gen = Rcpp::wrap(simple_smoothing_single_var(values, first_neighbors, second_neighbors, hex_indices));
    return rcpp_result_gen;
END_RCPP
}
// gaussian_smoothing_single_var
List gaussian_smoothing_single_var(NumericVector values, List first_neighbors, List second_neighbors, double center_weight, double first_order_weight, double second_order_weight, IntegerVector hex_indices);
RcppExport SEXP _hexsmoothR_gaussian_smoothing_single_var(SEXP valuesSEXP, SEXP first_neighborsSEXP, SEXP second_neighborsSEXP, SEXP center_weightSEXP, SEXP first_order_weightSEXP, SEXP second_order_weightSEXP, SEXP hex_indicesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< List >::type first_neighbors(first_neighborsSEXP);
    Rcpp::traits::input_parameter< List >::type second_neighbors(second_neighborsSEXP);
    Rcpp::traits::input_parameter< double >::type center_weight(center_weightSEXP);
    Rcpp::traits::input_parameter< double >::type first_order_weight(first_order_weightSEXP);
    Rcpp::traits::input_parameter< double >::type second_order_weight(second_order_weightSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type hex_indices(hex_indicesSEXP);
    rcpp_result_gen = Rcpp::wrap(gaussian_smoothing_single_var(values, first_neighbors, second_neighbors, center_weight, first_order_weight, second_order_weight, hex_indices));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_hexsmoothR_process_district_all_vars_n_orders", (DL_FUNC) &_hexsmoothR_process_district_all_vars_n_orders, 5},
    {"_hexsmoothR_process_district_all_vars", (DL_FUNC) &_hexsmoothR_process_district_all_vars, 6},
    {"_hexsmoothR_simple_smoothing_single_var", (DL_FUNC) &_hexsmoothR_simple_smoothing_single_var, 4},
    {"_hexsmoothR_gaussian_smoothing_single_var", (DL_FUNC) &_hexsmoothR_gaussian_smoothing_single_var, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_hexsmoothR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
