# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

process_district_all_vars_n_orders <- function(variable_values, neighbors, weights, hex_indices, var_names) {
    .Call('_hexsmoothR_process_district_all_vars_n_orders', PACKAGE = 'hexsmoothR', variable_values, neighbors, weights, hex_indices, var_names)
}

process_district_all_vars <- function(variable_values, first_neighbors, second_neighbors, weights, hex_indices, var_names) {
    .Call('_hexsmoothR_process_district_all_vars', PACKAGE = 'hexsmoothR', variable_values, first_neighbors, second_neighbors, weights, hex_indices, var_names)
}

simple_smoothing_single_var <- function(values, first_neighbors, second_neighbors, hex_indices) {
    .Call('_hexsmoothR_simple_smoothing_single_var', PACKAGE = 'hexsmoothR', values, first_neighbors, second_neighbors, hex_indices)
}

gaussian_smoothing_single_var <- function(values, first_neighbors, second_neighbors, center_weight, first_order_weight, second_order_weight, hex_indices) {
    .Call('_hexsmoothR_gaussian_smoothing_single_var', PACKAGE = 'hexsmoothR', values, first_neighbors, second_neighbors, center_weight, first_order_weight, second_order_weight, hex_indices)
}

